export { default as HeroHome } from "./HeroHome/HeroHome";
export { default as FeaturesHome } from "./FeaturesHome/FeaturesHome";
export { default as TechStackHome } from "./TechStackHome/TechStackHome";
export { default as TeamHome } from "./TeamHome/TeamHome";
export { default as OurProcess } from "./OurProcess/OurProcess";
export { default as OurClients } from "./OurClients/OurClients";
export { default as JoinTeam } from "./JoinTeam/JoinTeam";
export { default as OurWork } from "./OurWork/OurWork";
export { default as SolutionsHome } from "./SolutionsHome/SolutionsHome";
