
[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn next build"
publish = ".next"
[context.production]
  command = "nx affected:build --prod --deployUrl=\"$URL/\""

[context.deploy-preview]
  command = "nx affected:build --prod --deployUrl=\"$DEPLOY_PRIME_URL/\""