import Head from "next/head";
import Image from "next/image";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Robor.Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex, excepturi.
      </main>
    </div>
  );
};

export default Home;
